//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toltech.App.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toltech.App.Resources.Lang.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Absolute value.
        /// </summary>
        public static string AbsoluteValue {
            get {
                return ResourceManager.GetString("AbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse.
        /// </summary>
        public static string AnalyseWord {
            get {
                return ResourceManager.GetString("AnalyseWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creator: [Your Name], passionate about mechanical engineering, software development, and design tool optimization..
        /// </summary>
        public static string AppCreator {
            get {
                return ResourceManager.GetString("AppCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toltech is an BETA application designed to model tolerance chains using modern mathematical methods (matrices, screw theory, graphs...)..
        /// </summary>
        public static string AppDescription1 {
            get {
                return ResourceManager.GetString("AppDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developed with a user-centered approach, Toltech aims to make analyses accessible and automated, especially for SMEs..
        /// </summary>
        public static string AppDescription2 {
            get {
                return ResourceManager.GetString("AppDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application parameter.
        /// </summary>
        public static string ApplicationParameter {
            get {
                return ResourceManager.GetString("ApplicationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Theme.
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toltech - Tolerance Modeling Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exi.
        /// </summary>
        public static string BtnExi {
            get {
                return ResourceManager.GetString("BtnExi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graph.
        /// </summary>
        public static string BtnGraph {
            get {
                return ResourceManager.GetString("BtnGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isostaticity.
        /// </summary>
        public static string BtnIsostatisme {
            get {
                return ResourceManager.GetString("BtnIsostatisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MiP.
        /// </summary>
        public static string BtnMatrixPreview {
            get {
                return ResourceManager.GetString("BtnMatrixPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mod.
        /// </summary>
        public static string BtnMod {
            get {
                return ResourceManager.GetString("BtnMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parts.
        /// </summary>
        public static string BtnPart {
            get {
                return ResourceManager.GetString("BtnPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync.
        /// </summary>
        public static string BtnSync {
            get {
                return ResourceManager.GetString("BtnSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tol.
        /// </summary>
        public static string BtnTol {
            get {
                return ResourceManager.GetString("BtnTol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calculs.
        /// </summary>
        public static string CalculsWord {
            get {
                return ResourceManager.GetString("CalculsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to select one.
        /// </summary>
        public static string Click_to_select_one {
            get {
                return ResourceManager.GetString("Click_to_select_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contribution.
        /// </summary>
        public static string Contribution {
            get {
                return ResourceManager.GetString("Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contributions by requirement.
        /// </summary>
        public static string ContributionsByRequirement {
            get {
                return ResourceManager.GetString("ContributionsByRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string CopyWord {
            get {
                return ResourceManager.GetString("CopyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string CreateWord {
            get {
                return ResourceManager.GetString("CreateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default Unit.
        /// </summary>
        public static string DefaultUnit {
            get {
                return ResourceManager.GetString("DefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Degree (°).
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteWord {
            get {
                return ResourceManager.GetString("DeleteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag and drop an image here.
        /// </summary>
        public static string Drag_and_drop_an_image_here {
            get {
                return ResourceManager.GetString("Drag_and_drop_an_image_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate.
        /// </summary>
        public static string DuplicateWord {
            get {
                return ResourceManager.GetString("DuplicateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editing model -.
        /// </summary>
        public static string EditionModel {
            get {
                return ResourceManager.GetString("EditionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database error.
        /// </summary>
        public static string Error_Database {
            get {
                return ResourceManager.GetString("Error_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File locked by another application.
        /// </summary>
        public static string Error_FileLocked {
            get {
                return ResourceManager.GetString("Error_FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No active model..
        /// </summary>
        public static string Error_NoActiveModel {
            get {
                return ResourceManager.GetString("Error_NoActiveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Item not found.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access denied.
        /// </summary>
        public static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred.
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclude 0.
        /// </summary>
        public static string ExcludNull {
            get {
                return ResourceManager.GetString("ExcludNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Excel de la CrossTable.
        /// </summary>
        public static string Export_CrossTable_to_Excel {
            get {
                return ResourceManager.GetString("Export_CrossTable_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export CrossTable to Google Sheets.
        /// </summary>
        public static string Export_CrossTable_to_Google_Sheets {
            get {
                return ResourceManager.GetString("Export_CrossTable_to_Google_Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export (Resux).
        /// </summary>
        public static string Export_Resux {
            get {
                return ResourceManager.GetString("Export_Resux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to Excel.
        /// </summary>
        public static string Export_to_Excel {
            get {
                return ResourceManager.GetString("Export_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to GSheet.
        /// </summary>
        public static string Export_to_GSheet {
            get {
                return ResourceManager.GetString("Export_to_GSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected file: {0}.
        /// </summary>
        public static string FileSelectedMessage {
            get {
                return ResourceManager.GetString("FileSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays only the contribution from the end point of each component..
        /// </summary>
        public static string Filter_EndContribution {
            get {
                return ResourceManager.GetString("Filter_EndContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End contribution.
        /// </summary>
        public static string Filter_EndContribution_Content {
            get {
                return ResourceManager.GetString("Filter_EndContribution_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays only the contribution from intermediate elements of each component..
        /// </summary>
        public static string Filter_IntermediateContribution {
            get {
                return ResourceManager.GetString("Filter_IntermediateContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intermediate contribution.
        /// </summary>
        public static string Filter_IntermediateContribution_Content {
            get {
                return ResourceManager.GetString("Filter_IntermediateContribution_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays the item with the highest influence value for each requirement..
        /// </summary>
        public static string Filter_MaxInfluence {
            get {
                return ResourceManager.GetString("Filter_MaxInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum influence.
        /// </summary>
        public static string Filter_MaxInfluence_Content {
            get {
                return ResourceManager.GetString("Filter_MaxInfluence_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays the item with the lowest influence value for each requirement..
        /// </summary>
        public static string Filter_MinInfluence {
            get {
                return ResourceManager.GetString("Filter_MinInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum influence.
        /// </summary>
        public static string Filter_MinInfluence_Content {
            get {
                return ResourceManager.GetString("Filter_MinInfluence_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays only the contribution from the origin point of each component..
        /// </summary>
        public static string Filter_OriginContribution {
            get {
                return ResourceManager.GetString("Filter_OriginContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Origin contribution.
        /// </summary>
        public static string Filter_OriginContribution_Content {
            get {
                return ResourceManager.GetString("Filter_OriginContribution_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displays the sum of all components&apos; contributions to the final requirement value..
        /// </summary>
        public static string Filter_TotalContribution {
            get {
                return ResourceManager.GetString("Filter_TotalContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total contribution.
        /// </summary>
        public static string Filter_TotalContribution_Content {
            get {
                return ResourceManager.GetString("Filter_TotalContribution_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by :.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by name.
        /// </summary>
        public static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FREE-DIR Mode.
        /// </summary>
        public static string FREE_DIR_Mode {
            get {
                return ResourceManager.GetString("FREE_DIR_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string FrenchLabel {
            get {
                return ResourceManager.GetString("FrenchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DB Links.
        /// </summary>
        public static string GroupDatabaseLinks {
            get {
                return ResourceManager.GetString("GroupDatabaseLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Models.
        /// </summary>
        public static string GroupModels {
            get {
                return ResourceManager.GetString("GroupModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part.
        /// </summary>
        public static string GroupParts {
            get {
                return ResourceManager.GetString("GroupParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model path -.
        /// </summary>
        public static string GroupPathModel {
            get {
                return ResourceManager.GetString("GroupPathModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requirements.
        /// </summary>
        public static string GroupRequirements {
            get {
                return ResourceManager.GetString("GroupRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TOLTECH.
        /// </summary>
        public static string GroupTOLTECH {
            get {
                return ResourceManager.GetString("GroupTOLTECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Validation.
        /// </summary>
        public static string GroupValidation {
            get {
                return ResourceManager.GetString("GroupValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bar Chart.
        /// </summary>
        public static string Header_BarChart {
            get {
                return ResourceManager.GetString("Header_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide.
        /// </summary>
        public static string HideWord {
            get {
                return ResourceManager.GetString("HideWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string IDWord {
            get {
                return ResourceManager.GetString("IDWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import (.Resx).
        /// </summary>
        public static string Import_Resx {
            get {
                return ResourceManager.GetString("Import_Resx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inche (in).
        /// </summary>
        public static string Inche {
            get {
                return ResourceManager.GetString("Inche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Influence.
        /// </summary>
        public static string Influence {
            get {
                return ResourceManager.GetString("Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string InformationWord {
            get {
                return ResourceManager.GetString("InformationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italian.
        /// </summary>
        public static string ItalianLabel {
            get {
                return ResourceManager.GetString("ItalianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lauch.
        /// </summary>
        public static string LauchWord {
            get {
                return ResourceManager.GetString("LauchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toltech library.
        /// </summary>
        public static string LibraryToltech {
            get {
                return ResourceManager.GetString("LibraryToltech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local File.
        /// </summary>
        public static string LocalFolder {
            get {
                return ResourceManager.GetString("LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Density.
        /// </summary>
        public static string MasseVol {
            get {
                return ResourceManager.GetString("MasseVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Millimeters (mm).
        /// </summary>
        public static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model analyzed.
        /// </summary>
        public static string Model_analyzed {
            get {
                return ResourceManager.GetString("Model_analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Model.
        /// </summary>
        public static string ModelActif {
            get {
                return ResourceManager.GetString("ModelActif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The active model is already registered.
        /// </summary>
        public static string ModelAlreadyRegistered {
            get {
                return ResourceManager.GetString("ModelAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🟢 Model Currently Being Edited.
        /// </summary>
        public static string ModelCurrentlyBeingEdited {
            get {
                return ResourceManager.GetString("ModelCurrentlyBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        public static string ModifyWord {
            get {
                return ResourceManager.GetString("ModifyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        public static string MoveWord {
            get {
                return ResourceManager.GetString("MoveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data to display.
        /// </summary>
        public static string NoModelData1 {
            get {
                return ResourceManager.GetString("NoModelData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create or display the model.
        /// </summary>
        public static string NoModelData2 {
            get {
                return ResourceManager.GetString("NoModelData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data to display.
        /// </summary>
        public static string NoReqData1 {
            get {
                return ResourceManager.GetString("NoReqData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new requirement.
        /// </summary>
        public static string NoReqData2 {
            get {
                return ResourceManager.GetString("NoReqData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb part :.
        /// </summary>
        public static string NumberPart {
            get {
                return ResourceManager.GetString("NumberPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb requirement :.
        /// </summary>
        public static string NumberReq {
            get {
                return ResourceManager.GetString("NumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string OpenWord {
            get {
                return ResourceManager.GetString("OpenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview of parameters:.
        /// </summary>
        public static string ParamSentence {
            get {
                return ResourceManager.GetString("ParamSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed Part.
        /// </summary>
        public static string Part_Fixed {
            get {
                return ResourceManager.GetString("Part_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Fixed Part.
        /// </summary>
        public static string Part_NotFixed {
            get {
                return ResourceManager.GetString("Part_NotFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part 1.
        /// </summary>
        public static string Part1 {
            get {
                return ResourceManager.GetString("Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part 2.
        /// </summary>
        public static string Part2 {
            get {
                return ResourceManager.GetString("Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string Placeholder_Comment {
            get {
                return ResourceManager.GetString("Placeholder_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dir U.
        /// </summary>
        public static string Placeholder_DirX {
            get {
                return ResourceManager.GetString("Placeholder_DirX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dir V.
        /// </summary>
        public static string Placeholder_DirY {
            get {
                return ResourceManager.GetString("Placeholder_DirY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dir W.
        /// </summary>
        public static string Placeholder_DirZ {
            get {
                return ResourceManager.GetString("Placeholder_DirZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the punctual element.
        /// </summary>
        public static string Placeholder_NamePo {
            get {
                return ResourceManager.GetString("Placeholder_NamePo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the requirement.
        /// </summary>
        public static string Placeholder_NameReq {
            get {
                return ResourceManager.GetString("Placeholder_NameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coord X.
        /// </summary>
        public static string Placeholder_PointX {
            get {
                return ResourceManager.GetString("Placeholder_PointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coord Y.
        /// </summary>
        public static string Placeholder_PointY {
            get {
                return ResourceManager.GetString("Placeholder_PointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coord Z.
        /// </summary>
        public static string Placeholder_PointZ {
            get {
                return ResourceManager.GetString("Placeholder_PointZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tol 1.
        /// </summary>
        public static string Placeholder_Tol1 {
            get {
                return ResourceManager.GetString("Placeholder_Tol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolerance 1 description.
        /// </summary>
        public static string Placeholder_Tol1Desc {
            get {
                return ResourceManager.GetString("Placeholder_Tol1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of tolerance 1.
        /// </summary>
        public static string Placeholder_Tol1Name {
            get {
                return ResourceManager.GetString("Placeholder_Tol1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tol 2.
        /// </summary>
        public static string Placeholder_Tol2 {
            get {
                return ResourceManager.GetString("Placeholder_Tol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolerance 2 description.
        /// </summary>
        public static string Placeholder_Tol2Desc {
            get {
                return ResourceManager.GetString("Placeholder_Tol2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of tolerance 2.
        /// </summary>
        public static string Placeholder_Tol2Name {
            get {
                return ResourceManager.GetString("Placeholder_Tol2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tol Int.
        /// </summary>
        public static string Placeholder_TolInt {
            get {
                return ResourceManager.GetString("Placeholder_TolInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intermediate tolerance description.
        /// </summary>
        public static string Placeholder_TolIntDesc {
            get {
                return ResourceManager.GetString("Placeholder_TolIntDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of intermediate tolerance.
        /// </summary>
        public static string Placeholder_TolIntName {
            get {
                return ResourceManager.GetString("Placeholder_TolIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radian (rad).
        /// </summary>
        public static string RadianRad {
            get {
                return ResourceManager.GetString("RadianRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No valid active model.
        /// </summary>
        public static string Register_NoModel {
            get {
                return ResourceManager.GetString("Register_NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register the active model.
        /// </summary>
        public static string RegisterActiveModel {
            get {
                return ResourceManager.GetString("RegisterActiveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link Active Model.
        /// </summary>
        public static string RegisterActiveModelButton {
            get {
                return ResourceManager.GetString("RegisterActiveModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can save the active model or select a local file (.tolx) to add to the database..
        /// </summary>
        public static string RegisterModelDescription {
            get {
                return ResourceManager.GetString("RegisterModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register a Model.
        /// </summary>
        public static string RegisterModelHeader {
            get {
                return ResourceManager.GetString("RegisterModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register Model.
        /// </summary>
        public static string RegisterModelTitle {
            get {
                return ResourceManager.GetString("RegisterModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database.
        /// </summary>
        public static string RibbonTabDatabase {
            get {
                return ResourceManager.GetString("RibbonTabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model.
        /// </summary>
        public static string RibbonTabModel {
            get {
                return ResourceManager.GetString("RibbonTabModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter.
        /// </summary>
        public static string RibbonTabParameter {
            get {
                return ResourceManager.GetString("RibbonTabParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save model.
        /// </summary>
        public static string SaveModel {
            get {
                return ResourceManager.GetString("SaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a folder.
        /// </summary>
        public static string SelectFolderPathDefault {
            get {
                return ResourceManager.GetString("SelectFolderPathDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a .tolx file.
        /// </summary>
        public static string SelectTolxFile {
            get {
                return ResourceManager.GetString("SelectTolxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the requirements to be calculated:.
        /// </summary>
        public static string Sent_Select_the_requirements_to_be_calculated {
            get {
                return ResourceManager.GetString("Sent_Select_the_requirements_to_be_calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter bar.
        /// </summary>
        public static string SentFilterBar {
            get {
                return ResourceManager.GetString("SentFilterBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show.
        /// </summary>
        public static string ShowWord {
            get {
                return ResourceManager.GetString("ShowWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistical (RSS).
        /// </summary>
        public static string StatistiqueWord {
            get {
                return ResourceManager.GetString("StatistiqueWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Statut {
            get {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        public static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table type.
        /// </summary>
        public static string Table_type {
            get {
                return ResourceManager.GetString("Table_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modeling.
        /// </summary>
        public static string TabModeling {
            get {
                return ResourceManager.GetString("TabModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Models.
        /// </summary>
        public static string TabModels {
            get {
                return ResourceManager.GetString("TabModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requirements.
        /// </summary>
        public static string TabRequirements {
            get {
                return ResourceManager.GetString("TabRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Results.
        /// </summary>
        public static string TabResults {
            get {
                return ResourceManager.GetString("TabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à V3D.
        /// </summary>
        public static string TabV3D {
            get {
                return ResourceManager.GetString("TabV3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TestNeutral.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure that no active part positions this one..
        /// </summary>
        public static string TipCheckActiveParts {
            get {
                return ResourceManager.GetString("TipCheckActiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to copy.
        /// </summary>
        public static string TipCopyPath {
            get {
                return ResourceManager.GetString("TipCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new model.
        /// </summary>
        public static string TipCreateModel {
            get {
                return ResourceManager.GetString("TipCreateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a part.
        /// </summary>
        public static string TipCreatePart {
            get {
                return ResourceManager.GetString("TipCreatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a requirement.
        /// </summary>
        public static string TipCreateReq {
            get {
                return ResourceManager.GetString("TipCreateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a model.
        /// </summary>
        public static string TipDeleteModel {
            get {
                return ResourceManager.GetString("TipDeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a part.
        /// </summary>
        public static string TipDeletePart {
            get {
                return ResourceManager.GetString("TipDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a requirement.
        /// </summary>
        public static string TipDeleteReq {
            get {
                return ResourceManager.GetString("TipDeleteReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected part corresponds to the fixed part of the system (Base)..
        /// </summary>
        public static string TipFixedPart {
            get {
                return ResourceManager.GetString("TipFixedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link model to library.
        /// </summary>
        public static string TipLinkModel {
            get {
                return ResourceManager.GetString("TipLinkModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a model.
        /// </summary>
        public static string TipModifyModel {
            get {
                return ResourceManager.GetString("TipModifyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the file.
        /// </summary>
        public static string TipMoveModel {
            get {
                return ResourceManager.GetString("TipMoveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a model.
        /// </summary>
        public static string TipOpenModel {
            get {
                return ResourceManager.GetString("TipOpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolerance 1.
        /// </summary>
        public static string Tolerance1 {
            get {
                return ResourceManager.GetString("Tolerance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolerance 2.
        /// </summary>
        public static string Tolerance2 {
            get {
                return ResourceManager.GetString("Tolerance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INT Tolerance.
        /// </summary>
        public static string ToleranceInt {
            get {
                return ResourceManager.GetString("ToleranceInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tolx Files (*.tolx)|*.tolx.
        /// </summary>
        public static string TolxFileFilter {
            get {
                return ResourceManager.GetString("TolxFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The British flag, known as the Union Jack, combines elements of the flags of England, Scotland, and Ireland. It represents the historical union of these nations. The United Kingdom has had a profound global influence in science, literature, and industry. It is the birthplace of William Shakespeare, Isaac Newton, and the Industrial Revolution, and it continues to play a major role in international culture, finance, and education..
        /// </summary>
        public static string ToolTipFlag {
            get {
                return ResourceManager.GetString("ToolTipFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active part information.
        /// </summary>
        public static string ToolTipPart {
            get {
                return ResourceManager.GetString("ToolTipPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit.
        /// </summary>
        public static string UnitLabel {
            get {
                return ResourceManager.GetString("UnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Worst Case.
        /// </summary>
        public static string WorstCase {
            get {
                return ResourceManager.GetString("WorstCase", resourceCulture);
            }
        }
    }
}
