//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toltech.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class BarChartSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BarChartSettings defaultInstance = ((BarChartSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BarChartSettings())));
        
        public static BarChartSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16711936")]
        public int ColumnFill1Argb {
            get {
                return ((int)(this["ColumnFill1Argb"]));
            }
            set {
                this["ColumnFill1Argb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnFill2Argb {
            get {
                return ((int)(this["ColumnFill2Argb"]));
            }
            set {
                this["ColumnFill2Argb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnFill3Argb {
            get {
                return ((int)(this["ColumnFill3Argb"]));
            }
            set {
                this["ColumnFill3Argb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnOutlineArgb {
            get {
                return ((int)(this["ColumnOutlineArgb"]));
            }
            set {
                this["ColumnOutlineArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ColumnStrokeThickness {
            get {
                return ((float)(this["ColumnStrokeThickness"]));
            }
            set {
                this["ColumnStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineStrokeArgb {
            get {
                return ((int)(this["LineStrokeArgb"]));
            }
            set {
                this["LineStrokeArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LineStrokeThickness {
            get {
                return ((float)(this["LineStrokeThickness"]));
            }
            set {
                this["LineStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LineGeometrySize {
            get {
                return ((float)(this["LineGeometrySize"]));
            }
            set {
                this["LineGeometrySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineGeometryFillArgb {
            get {
                return ((int)(this["LineGeometryFillArgb"]));
            }
            set {
                this["LineGeometryFillArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineGeometryStrokeArgb {
            get {
                return ((int)(this["LineGeometryStrokeArgb"]));
            }
            set {
                this["LineGeometryStrokeArgb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideLineSerie {
            get {
                return ((bool)(this["HideLineSerie"]));
            }
            set {
                this["HideLineSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public float BarWidthThickness {
            get {
                return ((float)(this["BarWidthThickness"]));
            }
            set {
                this["BarWidthThickness"] = value;
            }
        }
    }
}
